 # .rubocop.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-rspec
  - rubocop-performance
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

# AllCops:
#   TargetRubyVersion: 3.0.1.1
# Lint/Env:
#   Enabled: true
#   Include:
#     - '**/*.rb'
#   Exclude:
#     - '**/config/environments/**/*'
#     - '**/config/application.rb'
#     - '**/config/environment.rb'
#     - '**/config/puma.rb'
#     - '**/config/boot.rb'
#     - '**/spec/*_helper.rb'
#     - '**/spec/**/support/**/*'
#     - 'lib/generators/**/*'
